language: objective-c
script:
 - xctool -workspace PinFever.xcworkspace -scheme PinFever -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO
 - xctool test -workspace PinFever.xcworkspace -scheme PinFeverTests -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO